### PR TITLE
Improved the smart contract response estimation to allow sufficient funds.

### PR DESCRIPTION
**Pull request by brendontoken**
EstimatedTransferResponse() was previously underestimating the funds required for the smart contract response. The funding calculation has also been coalesced to a single point nearer the end of the function to allow easier auditing of how the final funding amounts were determined.

### CODE REVIEW

**Comment by KarlTheProgrammer** [comment]
https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L398

Why are we looking at senders when calculating outputs for BSV receivers? There can be multiple senders to a different number of receivers. We should only need to add receivers.

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L385
https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L438

The indexes are fairly predictable and should be accurate enough that adding extra value to them should not be necessary.

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L393
https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L452

I don't think we need to add funding for non-existent senders/receivers. It was originally only setup to estimate funding for the existing parts of the transfer. I assume this is for incomplete requests. The request recipient can add funding for their own data in the transfer since we won't really be able to predict exactly how they will send/receive anyway. It could be more than one sender/receiver, or in the future, locking scripts of different sizes.

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L489

I may have had this part wrong before. I don't think we need the `wire.VarIntSerializeSize(uint64(i))` here. I don't think we need a loop and can just multiply the input size by the count and we just need a `txSizeInputs += wire.VarIntSerializeSize(uint64(p2PKHInputCount))` to account for the serialization of the number of inputs in the tx. Any variable size serialization within the input should already be accounted for in the `MaximumP2PKHInputSize` value.

I think we also need to add the output count serialization size to this section.

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L505

It looks like the funding for BSV is being added to the index of the BSV asset (of the transfer assets), which is not associated with a contract. You should only provide funding to contract outputs.

I am not sure I see any changes that actually fixed a funding estimation issue. The request recipients should be adjusting the funding before proceeding. If you have some examples of short funding and specific fixes it might be more clear.

**Comment by brendontoken** [comment]
Thanks for the thorough review. Here are my thoughts / what I can remember:

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L398
Not sure why you think senders are out of place here. This part of the function is calculating outputs for senders. Receivers are handled below, from line 409 onward.

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L385
https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L438
I came across an instance where the index in the response was 1 higher than used for the estimation, so thought it best to overestimate here. This may have been when it was not correctly allocating earlier outputs, so there is a possibility this is no longer needed. I see leaving it in as erring on the side of caution.

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L393
https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L452
I guess this is just to make it "less wrong". There must be at least one sender and one receiver. An estimation that doesn't include those will definitely be an underestimation, which is the case we want to avoid.

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L505
My understanding from the comments above the function, and the way the returned value is used, is that it is supposed to be funding per asset, rather than funding per output. The consumer of this function does allocate the BSV transfer costs to a contract output, as you suggest.

By the time I refactored my changes to the function, I'm not sure how the changes fix the funding estimation either. ;-) I do know that I had underestimation problems with the previous version of the function, but not the current version.  After I had refactored everything, I did an isolated test where I changed only the `specification` version and had underestimation problems when using the previous version. Since the previous version built up the estimation gradually it is difficult to isolate the error. The current version does all the calculations in one place, so it is easier to find any problems and fix.

**Comment by KarlTheProgrammer** [comment]
> Not sure why you think senders are out of place here. This part of the function is calculating outputs for senders. Receivers are handled below, from line 409 onward.

BSV senders don't get outputs, do they? So we don't need to do anything there.

> I came across an instance where the index in the response was 1 higher than used for the estimation, so thought it best to overestimate here.

This is probably okay, though I think the only real issue would be between zero and one. If we specify the index at zero, then protobuf excludes the entire field, so if it ends up being one in the response, we will be a few bytes short. Anything from 1-127 will all be the same size in the protobuf response because of the base128 var int encoding.

> I guess this is just to make it "less wrong". There must be at least one sender and one receiver. An estimation that doesn't include those will definitely be an underestimation, which is the case we want to avoid.

You are correct. I guess that is better. It also means if the request recipient responds with as minimal response as possible (single inputs and outputs), they might not need to add any funding. It is probably good convention to have the request initiator fund as much as possible.

However, I think the 2 sections linked below (one of which was already there) will cause the request initiator to fund the bitcoin for the transfer when they are requesting bitcoin be sent to them. I think we need to change it so the bitcoin transfer funding is based on the senders. So if you send a request with bitcoin senders (you want to send bitcoin), it tells you to fund the bitcoin for the transfer via the master contract, but if you send a request with bitcoin receivers (you want to receive bitcoin), it doesn't. This could have been an issue you were having before.

https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L430
https://github.com/tokenized/specification/blob/c123c1741323203951c625ee2353ec5bc84841c7/dist/golang/protocol/fees.go#L461 


> My understanding from the comments above the function, and the way the returned value is used, is that it is supposed to be funding per asset, rather than funding per output. The consumer of this function does allocate the BSV transfer costs to a contract output, as you suggest.

Yes, the funding is per asset structure in the transfer action, but that is to allow it to line up with the contracts for those assets. BSV does not have a contract to fund. The `ContractIndex` for BSV transfers is "left blank", since there is no contract, so defaults to zero (by protobuf rules), which is supposed to be ignored because it is just the first input, which can be anything. In the link below you can see that it is adding the funding to the output at the `ContractIndex` for each asset. The way we do it, that is the first contract (which should receive the funding), but that is not required by the protocol, so that could technically be any output. The funding for BSV needs to be added to the output for the "master" contract `fundingForBSV[masterContractIndex]`.

https://github.com/tokenized/nexus-api/blob/c61bd9a2474dff56dc38bbbe05a514bb7c923d22/internal/builder/approve.go#L578


> I've also realised that this does not correctly handle multiple OP_RETURNS yet. Perhaps we can leave that until a later date.

Since transfers allow multiple asset transfers within them, I am not sure we need to support multiple op returns. If there is a metadata op return or something it is not part of the settlement response, so does not need to be included in this calculation. Unless we add some rule for the contract to carry that data over to the response.

**Comment by brendontoken** [comment]
You have a couple of good points. I'll look into it.

**Pull request merged**
